### ISSUE TITLE
Issue with 'content_hash' field

### ISSUE THREAD

**Issue by buster60** [Vinz87/TndrAssistant#2]
Hey,
While trying to run the utility I ran into two problems so far.
First, I had the same issue as gargomoma with the Facebook login. I got around it by creating the access_token.txt myself.

Later, the following exception occurred:
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\TndrAssistant-master\TndrAssistant.py", line 151, in <module>
    match_candidate_hash_list.append(user.content_hash)
AttributeError: 'Hopeful' object has no attribute 'content_hash'
```

I saw that you introduced this in version 2.1. I also tried looking at pyndr's user.py and saw it indeed has no content_hash field. Hopeful also has a like() function which can be called without having to use ._session.

I will look more into it and verify my conclusions but maybe you already know how to fix the problem yourself by now.
Thanks

**Comment by Vinz87** [comment]
Sorry, I forgot to write you have to use [my fork](https://github.com/Vinz87/pynder) of pynder, where I added those additional fields in the like() requests.
A user noticed that those fields have been added in the original requests in the Tinder app, therefore I opened a pull request with these modifications to the original pynder repository. However, for now they are available only in my fork.
