### ISSUE TITLE
I think the browser page opened is faulty

### ISSUE THREAD

**Issue by buster60** [Vinz87/TndrAssistant#3]
After fixing previous issues and also setting up a DB, I ran TndrAssistant.py without errors (or any other output). I then ran 
`TndrAssistant.py` --pics m
And the following webpage opened:
![image](https://cloud.githubusercontent.com/assets/24945195/21717247/8360a8a8-d418-11e6-9d45-9c98d78b6dda.png)
I am not sure if a php environment was needed or how should it look.
Thanks!

**Comment by Vinz87** [comment]
It looks like the webpage opens correctly, it is simply empty, it has no user to show. Did the script find any match candidate? Is there in the DB any record with the match_candidate flag equal to 1?

If not, you can run it with the parameter `--pics r` to show all users stored since today.

**Comment by buster60** [comment]
Could it be because I didn't use the --store option? Now I  used it and then ran` --pics all` and the page showed succesfuly.

**Comment by Vinz87** [comment]
Yes, if you don't use `--store` the DB is ignored; the script fetch new users, looks for match candidate, and auto-like them and/or notifies you according to the config file.
`--pics` works with the users stored in the DB, unless you provide a particular user_id
