### ISSUE TITLE
--like error

### ISSUE THREAD

**Issue by buster60** [Vinz87/TndrAssistant#4]
Calling `TndrAssistant.py --like 573` raises the error
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\TndrAssistant-master\TndrAssistant.py", line 271, in <module>
    id, hash, s_number = user_triplet.split("_")
ValueError: need more than 1 value to unpack
```
Which makes sense because usage wants only id to be given.
Again I will try to look into how it can be fixed.

**Comment by buster60** [comment]
Updating that I presumably fixed the issue in the following way:
```
	if args.like:
		# USER LIKE
		if DB_NAME:
			#for user_triplet in args.like:
			for id in args.like:
				#id, hash, s_number = user_triplet.split("_")
				cur.execute('SELECT user_id, content_hash, s_number FROM TndrAssistant WHERE user_id = "%s" ORDER BY list_index ASC' % id)
				temp_list = cur.fetchall()
				user_list = []
				for i in range(len(temp_list)):
					user_list.append(temp_list[i][0])
				print temp_list
				assert len(set(user_list)) == 1
				#res = session._api.like(id, user.hash, user.s_number)
				res = session._api.like(*temp_list[0])
```
But I am not entirely sure it's working, because I didn't match with anyone from my match suggestion list, except for those whom I was  already matched with, and the "likes_remaining" always stayed at 100:
`{úlikes_remaining': 100, úmatch': False}`

**Comment by Vinz87** [comment]
The argument when using the `--like` parameter is a string like "id_contenthash_snumber".

This string is generated automatically for you when using the webpage generated with the `--pics` parameter. 

If you want to provide it manually you should write it in that way, therefore picking the user id, the content hash value, and the s number value (no one knows exactly what they are, except from being fields of the like request in the original Tinder app), concatenating them with an underscore "_".

**Comment by buster60** [comment]
Sorry for the misunderstanding, but the "573" was truncated, it was a 24 digit hex number. Appearing in the page like so:
ID: 573************************
So I guess the problem is that I don't see where the contenthash and s_number appear in the webpage (they don't seem to be concatenated to the ID!)

**Comment by Vinz87** [comment]
Ok, that is only the id; if you use the radio buttons to select a like, then click the send button, there complete string will appear, provided you set up a PHP environment.

If a PHP environment is not set up, you should do it manually, in that case I could modify the webpage in order to make it appear also the content hash and s number values, so one can copy them manually.

**Comment by buster60** [comment]
I am updating liking using your method (with the 3 parameters) doesn't work as well: I get the same issue
`{u'likes_remaining': 100, u'match': False}`

**Comment by Vinz87** [comment]
That is not an issue, it means you have liked the user but it's not a match.
Match candidates are indeed _candidates_, there's a chance you get multiple appearances of that users not because he/she has liked you. Most of them, anyway, should result in a match, at least this is what I noticed.

**Comment by buster60** [comment]
I see. I will get more observations but as of now none have been matches.
Also, what about the likes remaining? It should decrease.

**Comment by Vinz87** [comment]
I never saw it decreasing, even after successful matches. I think you'll see it start decreasing if you like a very large number of users
