### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by halalfood** [Vinz87/TndrAssistant#9]
Keep getting this error and don't know how to resolve. 

Traceback (most recent call last):
  File "C:/Users/#######/Desktop/TndrAssistant-master/TndrAssistant.py", line 203, in <module>
    res = session._api.like(id, content_hash, s_number)
NameError: name 'session' is not defined

**Comment by Vinz87** [comment]
it should be solved with last version 2.4.2, it was a portion left unedited after last major upgrade
